//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Image_Project.dbconnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product12
    {
        public int ProdId { get; set; }
        public string ProdName { get; set; }
        public Nullable<int> ProdRate { get; set; }
        public Nullable<int> ProdQty { get; set; }
        public string ProdTotal { get; set; }
        public string ProdImage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
